# ------------------- Item Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  name: order
  namespace: micro-obs
  labels:
    app: order
    service: order
spec:
  type: NodePort
  selector:
    app: order
    service: order
  ports:
  - name: http
    protocol: TCP
    port:  8090
    targetPort: http
    nodePort: 30809
---

# ------------------- Item Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order
  namespace: micro-obs
  labels:
    app: order
    service: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      service: order
  template:
    metadata:
      labels:
        app: order
        service: order
    spec:
      containers:
      - name: order
        image: obitech/micro-obs:v0.2.2
        env:
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent.monitoring.svc.cluster.local
          - name: JAEGER_AGENT_PORT
            value: "6831"
        command: ["order"]
        args: [
          "-r", "redis://redis-order:6379/0", 
          "-i", "http://item.micro-obs.svc.cluster.local:8080"
        ]
        ports:
        - name: http
          containerPort: 8090
---

# ------------------- Item ServiceMonitor ------------------- #
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order
  namespace: micro-obs
  labels:
    app: order
    service: order
spec:
  selector:
    matchLabels:
      app: order
      service: order
  endpoints:
  - port: http