global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'item'
  static_configs:
  - targets: ['item:8080']

- job_name: 'order'
  static_configs:
  - targets: ['order:8090']

- job_name: 'redis_exporter'
  static_configs:
  - targets: ['redis-exporter:9121']

- job_name: 'jaeger'
  static_configs:
  - targets: ['jaeger:16686']

- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'grafana'
  static_configs:
  - targets: ['grafana:3000']



